- hosts: metric_server
  become: yes
  vars:
    grafana_rpm: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.1.3-1.x86_64.rpm 
    telegraf_rpm: https://dl.influxdata.com/telegraf/releases/telegraf-1.6.3-1.x86_64.rpm
    influxdb_rpm: https://dl.influxdata.com/influxdb/releases/influxdb-1.5.2.x86_64.rpm
  tasks:
    - name: "install influx db"
      yum:
        name: "{{influxdb_rpm}}"
        state: present
    - name: "restart influx"
      service:
        enabled: yes
        name: influxdb
        state: restarted
    - yum:
        name: "{{telegraf_rpm}}"
    - service:
        name: telegraf
        state: restarted
        enabled: yes
    - yum:
        name: "{{grafana_rpm}}"
    - service:
        state: restarted
        enabled: yes
        name: grafana-server
